name: Build and deploy Python app to Azure Web App - product-service-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Deploy ONLY the Flask service subfolder (monorepo)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-service-app'                  # <-- your exact Web App name
          slot-name: 'Production'
          package: 'Lab3/product-service-lab3'             # <-- subfolder with app.py & requirements.txt
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PRODUCT_SERVICE_APP }}
